server:
  port: 8082

spring:
  application:
    name:
      QUESTION-SERVICE

  # Database Config:
  datasource:
    url: jdbc:mysql://localhost:3306/question_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 169251
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Config as a eureka client:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/