server:
  port: 8081
spring:
  application:
    name: QuizService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz_service_db
    username: root
    password: 169251
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
